### ISSUE TITLE
Error when generating scaffold for multiple tables

### ISSUE THREAD

**Issue by jaffacake** [frenesim/schema_to_scaffold#14]
I'm trying to generate scaffolds for about 300 tables and your tool would be very useful, however when trying to do multiple tables I get the error below. Doing 1 table at a time seems to work fine.

/Users/grant/.rvm/gems/ruby-2.1.2/gems/schema_to_scaffold-0.5.2/lib/schema_to_scaffold/table.rb:15:in `map': undefined method`to_script' for nil:NilClass (NoMethodError)
    from /Users/grant/.rvm/gems/ruby-2.1.2/gems/schema_to_scaffold-0.5.2/lib/schema_to_scaffold/table.rb:15:in `to_script'
    from /Users/grant/.rvm/gems/ruby-2.1.2/gems/schema_to_scaffold-0.5.2/lib/schema_to_scaffold.rb:84:in`generate_script'
    from /Users/grant/.rvm/gems/ruby-2.1.2/gems/schema_to_scaffold-0.5.2/bin/scaffold:56:in `block in <top (required)>'
    from /Users/grant/.rvm/gems/ruby-2.1.2/gems/schema_to_scaffold-0.5.2/bin/scaffold:56:in`each'
    from /Users/grant/.rvm/gems/ruby-2.1.2/gems/schema_to_scaffold-0.5.2/bin/scaffold:56:in `<top (required)>'
    from /Users/grant/.rvm/gems/ruby-2.1.2/bin/scaffold:23:in`load'
    from /Users/grant/.rvm/gems/ruby-2.1.2/bin/scaffold:23:in `<main>'
    from /Users/grant/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in`eval'
    from /Users/grant/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'

**Comment by reiallenramos** [comment]
Hi I recently had the same problem. The gem successfully copied the generated scaffold command to my clipboard but when I pasted it to my text editor, the "\n"s were missing like so: "rails generate scaffold Cuprails generate scaffold Noodlesrails generate ...". When I manually put space in between "Cup" and "rails", then run the complete command (355 scaffolds for 355 tables), it just run the very first one, just like in this issue. So to solve this I manually added "&& " in between all the rails scaffold commands such that they would look like this: "rails generate scaffold Cup && rails generate scaffold Noodles && ..." When I run the command again, problem solved!

Note: I wasn't able to take note of the duration that the 355 scaffolds ran, but when I went out for lunch and came back, it was done. So that's maximum 1 hour.
